### ISSUE TITLE
Access violation on FormatLogEntry

### ISSUE THREAD

**Issue by TETYYS** [processhacker2/processhacker2#54] opened 2016-08-11 08:44 UTC
Sorry for providing little information, but all I have is call stack:

```
000000006aefb00c()
user32.dll!UserCallWinProcCheckWow()
user32.dll!DispatchMessageWorker()
ProcessHacker.exe!PhFormatLogEntry() + 5841 bytes
ProcessHacker.exe!PhFormatLogEntry() + 5507 bytes
Processhacker.exe!PhVerifyFile() + 9742 bytes
kernel32.dll!BaseThreadInitThunk()
ntdll.dll!RtlUserThreadStart()
```
I was fiddling around with UltraMon (actually it crashed at the moment I disabled smart task bar while PH was at second monitor), and last call memory was [deallocated](http://i.imgur.com/yB8JkcF.png) at the time debugger started so I guess it could be some kind of UltraMon injected dll. Only interesting thing is that PH was only application that crashed.

**Comment by dmex** [comment] 2016-08-11 09:20
That call stack doesn't make much sense since PH and plugins don't call PhVerifyFile anywhere?

**Comment by TETYYS** [comment] 2016-08-11 16:12
wow very strange

**Comment by dmex** [comment] 2016-08-20 03:52
I'm closing this since I can't reproduce but feel free to reopen... I would also report this to the UltraMon developers since it appears to be a problem with their injected code.

**Closed by dmex** 2016-08-20 03:52 UTC
